applications:
    name: event-service
    host: event-cloud-service
    memory: 512M
    services:
	  - registry-service
      - config-service
      - mysql-service
    path: target/event-service-0.0.1-SNAPSHOT.jar
    env:
      SPRING_PROFILES_ACTIVE: prod