spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  datasource:
    platform: h2
    continue-on-error: false
    initialize: true
    driver-class-name: org.h2.Driver
