spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  datasource:
    platform: h2
    continue-on-error: false
    initialize: true
    url: jdbc:h2:tcp://localhost:9091/mem:lawyer-db;
    username: sa
    password: null
    driver-class-name: org.h2.Driver